name: RKNN Model Conversion Test
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: install dependencies
      run: sudo apt-get update -y && sudo apt-get install -y python3-pip git libsm6 --no-install-recommends -y && python -m pip install -r requirements.txt && git lfs install
    - name: Clone model LABSE-Vit-L-14
      run: git clone https://huggingface.co/immich-app/LABSE-Vit-L-14 --depth 1
        LABSE-Vit-L-14
    - name: Run textual build script for LABSE-Vit-L-14 on rk3588
      run: python3 build_rknn.py LABSE-Vit-L-14/ rk3588
    - name: Upload textual artifact for LABSE-Vit-L-14 on rk3588
      uses: actions/upload-artifact@v4
      with:
        name: LABSE-Vit-L-14-textual-rk3588.rknn
        path: LABSE-Vit-L-14/textual/rk3588.rknn
    - name: Upload visual artifact for LABSE-Vit-L-14 on rk3588
      uses: actions/upload-artifact@v4
      with:
        name: LABSE-Vit-L-14-visual-rk3588.rknn
        path: LABSE-Vit-L-14/visual/rk3588.rknn

    
on:
  pull_request:
    branches:
    - unificli
  push:
    branches:
    - unificli
