name: RKNN Model Conversion Test
jobs:
  run-python-script:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: 'python3 -m pip install --upgrade pip setuptools
        pip install -r requirements.txt
        sudo apt-get update -y
        sudo apt-get install git libsm6 -y
        git lfs install
        '
    - name: Clone model LABSE-Vit-L-14
      run: git clone https://huggingface.co/immich-app/LABSE-Vit-L-14 --depth 1
        LABSE-Vit-L-14
    - name: Run textual build script for LABSE-Vit-L-14 on rk3588
      run: python3 build_rknn.py LABSE-Vit-L-14/textual/model.onnx rk3588
    - name: Upload textual artifact for LABSE-Vit-L-14 on rk3588
      uses: actions/upload-artifact@v4
      with:
        name: LABSE-Vit-L-14-textual-rk3588.rknn
        path: LABSE-Vit-L-14/textual/rk3588.rknn
    - name: Remove uploaded textual model for LABSE-Vit-L-14 on rk3588
      run: rm LABSE-Vit-L-14/textual/rk3588.rknn
    - name: Run visual build script for LABSE-Vit-L-14 on rk3588
      run: python3 build_rknn.py LABSE-Vit-L-14/visual/model.onnx rk3588
    - name: Upload visual artifact for LABSE-Vit-L-14 on rk3588
      uses: actions/upload-artifact@v4
      with:
        name: LABSE-Vit-L-14-visual-rk3588.rknn
        path: LABSE-Vit-L-14/visual/rk3588.rknn
    - name: Remove uploaded visual model for LABSE-Vit-L-14 on rk3588
      run: rm LABSE-Vit-L-14/visual/rk3588.rknn
    
name: Run Python Build Script
on:
  pull_request:
    branches:
    - unificli
  push:
    branches:
    - unificli
